### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shrekshao** [shrekshao/AnimationSketcher#2]
# General goal
- [x] Get a Model
- [x] Add selected Curve to GUI.

**Comment by shrekshao** [comment]
s

**Comment by davidgrosman** [comment]
- [x] Add ASketcherNode for faster prototyping with Maya.
- [x] Curve drawing, parameters getting, projection (from top, side, front viewport)

**Comment by davidgrosman** [comment]
Hello

**Comment by shrekshao** [comment]
- [x] Menu (Graph chart) S
